### ISSUE TITLE
Button goes down the screen.

### ISSUE THREAD

**Issue by Jarmander333** [Siembiedak/Random-Color-Generator#1]
The "Change Color" button the first time you click it is at the top of the screen, and then goes down by a few pixels.  A solution is that before you press the button, you could display the "HEX VALUE:" as "#FFFFFF" because the background is white.  

"Remove one bug from a program, 2 more are born."

 - Jarmander333

**Comment by Siembiedak** [comment]
Should be fixed now. Thank you for the help.
